# Generated by Django 5.1.5 on 2025-01-20 09:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storeapp', '0003_alter_userprofile_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='BasketModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordered', models.BooleanField(default=False)),
                ('count', models.ImageField(default=1, upload_to='')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='storeapp.userprofile')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='storeapp.productmodel')),
            ],
        ),
    ]
