# Generated by Django 5.1.5 on 2025-01-20 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storeapp', '0004_basketmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basketmodel',
            name='count',
            field=models.IntegerField(default=1),
        ),
    ]
