# Generated by Django 5.1.5 on 2025-01-22 09:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storeapp', '0005_alter_basketmodel_count'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('Yetkazilmoqda', 'Yetkazilmoqda'), ('Yetkazildi', 'Yetkazildi'), ("To'landi", "To'landi")], max_length=200)),
                ('basket', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='storeapp.basketmodel')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='storeapp.userprofile')),
            ],
        ),
    ]
