# Generated by Django 5.1.5 on 2025-01-22 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storeapp', '0006_ordermodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordermodel',
            name='basket',
        ),
        migrations.AddField(
            model_name='ordermodel',
            name='basket',
            field=models.ManyToManyField(to='storeapp.basketmodel'),
        ),
    ]
