# Generated by Django 5.1.5 on 2025-01-22 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storeapp', '0008_ordermodel_address_ordermodel_first_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordermodel',
            name='status',
            field=models.CharField(blank=True, choices=[('Yetkazilmoqda', 'Yetkazilmoqda'), ('Yetkazildi', 'Yetkazildi'), ("To'landi", "To'landi")], max_length=200, null=True),
        ),
    ]
