# Generated by Django 5.1.5 on 2025-01-22 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storeapp', '0009_alter_ordermodel_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordermodel',
            name='summa',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
