# Generated by Django 5.1.5 on 2025-01-24 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storeapp', '0010_ordermodel_summa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordermodel',
            name='phone',
            field=models.CharField(blank=True, max_length=13, null=True),
        ),
    ]
